# --- Experiment configurations --------------------------------------------------------------------

# experiment name, used as folder name
experiment_name: LSTM-150C

# place to store run directory (if empty runs are stored in $cwd$/runs/)
run_dir:

# files to specify training, validation and test basins (relative to code root or absolute path), correct for your path
train_basin_file: basin_lists/NC/basins_150.txt
validation_basin_file: basin_lists/NC/basins_150.txt
test_basin_file: basin_lists/Uba_basin.txt

# training, validation and test time periods (format = 'dd/mm/yyyy')
train_start_date: "01/01/1995"
train_end_date: "31/01/2009"
validation_start_date: "01/01/2010"
validation_end_date: "31/12/2011"
test_start_date: "01/01/2012"
test_end_date: "30/11/2020"

# fixed seed, leave empty to use a random seed
seed: 123

# which GPU (id) to use [in format of cuda:0, cuda:1 etc, or cpu, mps or None]
device: cuda:0

# --- Validation configuration ---------------------------------------------------------------------

# specify after how many epochs to perform validation
validate_every: 1

# specify how many random basins to use for validation
validate_n_random_basins: 150

# specify which metrics to calculate during validation
metrics:
- NSE

# --- Model configuration --------------------------------------------------------------------------

# base model type
model: cudalstm

# prediction head [regression, mdn, umal]. Define the head specific parameters below
head: regression

# ----> General settings <----

# Number of cell states of the LSTM
hidden_size: 256

# Initial bias value of the forget gate
initial_forget_bias: 3

# Dropout applied to the output of the LSTM
output_dropout: 0.4

output_activation: linear

# --- Training configuration -----------------------------------------------------------------------

# specify optimizer [Adam, Adadelta]
optimizer: Adam

# specify loss [MSE, NSE, RMSE, UMALLoss, MDNLoss]
loss: MSE

# specify learning rates to use starting at specific epochs (0 is the initial learning rate)
learning_rate: 5e-4

# Mini-batch size
batch_size: 256

# Number of training epochs
epochs: 50

# If True, clips norm of gradients
clip_gradient_norm: 1

# Defines which time steps are used to calculate the loss. Can't be larger than seq_length
predict_last_n: 7

# Length of the input sequence
seq_length: 365

# Number of parallel workers used in the data pipeline
num_workers: 8

# Log the training loss every n steps
log_interval: 5

# If true, writes logging results into tensorboard file
log_tensorboard: True

# Save model weights every n epochs
save_weights_every: 1

# Store the results of the validation to disk
save_validation_results: True

# --- Data configurations --------------------------------------------------------------------------

dataset: caravan

# Provide path to the caravan dataset embedded with local data
data_dir: <ABSOLUTE_PATH_TO_CARAVAN>


# variables to use as time series input 
dynamic_inputs:
  - dewpoint_temperature_2m_max
  - dewpoint_temperature_2m_mean
  - dewpoint_temperature_2m_min
  - potential_evaporation_sum_ERA5_LAND
  - potential_evaporation_sum_FAO_PENMAN_MONTEITH
  - snow_depth_water_equivalent_max
  - snow_depth_water_equivalent_mean
  - snow_depth_water_equivalent_min
  - surface_net_solar_radiation_max
  - surface_net_solar_radiation_mean
  - surface_net_solar_radiation_min
  - surface_net_thermal_radiation_max
  - surface_net_thermal_radiation_mean
  - surface_net_thermal_radiation_min
  - surface_pressure_max
  - surface_pressure_mean
  - surface_pressure_min
  - temperature_2m_max
  - temperature_2m_mean
  - temperature_2m_min
  - total_precipitation_sum
  - u_component_of_wind_10m_max
  - u_component_of_wind_10m_mean
  - u_component_of_wind_10m_min
  - v_component_of_wind_10m_max
  - v_component_of_wind_10m_mean
  - v_component_of_wind_10m_min
  - volumetric_soil_water_layer_1_max
  - volumetric_soil_water_layer_1_mean
  - volumetric_soil_water_layer_1_min
  - volumetric_soil_water_layer_2_max
  - volumetric_soil_water_layer_2_mean
  - volumetric_soil_water_layer_2_min
  - volumetric_soil_water_layer_3_max
  - volumetric_soil_water_layer_3_mean
  - volumetric_soil_water_layer_3_min
  - volumetric_soil_water_layer_4_max
  - volumetric_soil_water_layer_4_mean
  - volumetric_soil_water_layer_4_min

# which columns to use as target
target_variables:
- streamflow

static_attributes:
  - aet_mm_s01
  - aet_mm_s02
  - aet_mm_s03
  - aet_mm_s04
  - aet_mm_s05
  - aet_mm_s06
  - aet_mm_s07
  - aet_mm_s08
  - aet_mm_s09
  - aet_mm_s10
  - aet_mm_s11
  - aet_mm_s12
  - aet_mm_syr
  - area_fraction_used_for_aggregation
  - ari_ix_sav
  - cls_cl_smj
  - cly_pc_sav
  - clz_cl_smj
  - cmi_ix_s01
  - cmi_ix_s02
  - cmi_ix_s03
  - cmi_ix_s04
  - cmi_ix_s05
  - cmi_ix_s06
  - cmi_ix_s07
  - cmi_ix_s08
  - cmi_ix_s09
  - cmi_ix_s10
  - cmi_ix_s11
  - cmi_ix_s12
  - cmi_ix_syr
  - crp_pc_sse
  - dis_m3_pmn
  - dis_m3_pmx
  - dis_m3_pyr
  - dor_pc_pva
  - ele_mt_sav
  - ele_mt_smn
  - ele_mt_smx
  - ero_kh_sav
  - fec_cl_smj
  - fmh_cl_smj
  - for_pc_sse
  - gdp_ud_sav
  - gdp_ud_ssu
  - gla_pc_sse
  - glc_cl_smj
  - glc_pc_s01
  - glc_pc_s02
  - glc_pc_s03
  - glc_pc_s04
  - glc_pc_s05
  - glc_pc_s06
  - glc_pc_s07
  - glc_pc_s08
  - glc_pc_s09
  - glc_pc_s10
  - glc_pc_s11
  - glc_pc_s12
  - glc_pc_s13
  - glc_pc_s14
  - glc_pc_s15
  - glc_pc_s16
  - glc_pc_s17
  - glc_pc_s18
  - glc_pc_s19
  - glc_pc_s20
  - glc_pc_s21
  - glc_pc_s22
  - gwt_cm_sav
  - hdi_ix_sav
  - hft_ix_s09
  - hft_ix_s93
  - inu_pc_slt
  - inu_pc_smn
  - inu_pc_smx
  - ire_pc_sse
  - kar_pc_sse
  - lit_cl_smj
  - lka_pc_sse
  - lkv_mc_usu
  - nli_ix_sav
  - pac_pc_sse
  - pet_mm_s01
  - pet_mm_s02
  - pet_mm_s03
  - pet_mm_s04
  - pet_mm_s05
  - pet_mm_s06
  - pet_mm_s07
  - pet_mm_s08
  - pet_mm_s09
  - pet_mm_s10
  - pet_mm_s11
  - pet_mm_s12
  - pet_mm_syr
  - pnv_cl_smj
  - pnv_pc_s01
  - pnv_pc_s02
  - pnv_pc_s03
  - pnv_pc_s04
  - pnv_pc_s05
  - pnv_pc_s06
  - pnv_pc_s07
  - pnv_pc_s08
  - pnv_pc_s09
  - pnv_pc_s10
  - pnv_pc_s11
  - pnv_pc_s12
  - pnv_pc_s13
  - pnv_pc_s14
  - pnv_pc_s15
  - pop_ct_usu
  - ppd_pk_sav
  - pre_mm_s01
  - pre_mm_s02
  - pre_mm_s03
  - pre_mm_s04
  - pre_mm_s05
  - pre_mm_s06
  - pre_mm_s07
  - pre_mm_s08
  - pre_mm_s09
  - pre_mm_s10
  - pre_mm_s11
  - pre_mm_s12
  - pre_mm_syr
  - prm_pc_sse
  - pst_pc_sse
  - rdd_mk_sav
  - rev_mc_usu
  - ria_ha_usu
  - riv_tc_usu
  - run_mm_syr
  - sgr_dk_sav
  - slp_dg_sav
  - slt_pc_sav
  - snd_pc_sav
  - snw_pc_s01
  - snw_pc_s02
  - snw_pc_s03
  - snw_pc_s04
  - snw_pc_s05
  - snw_pc_s06
  - snw_pc_s07
  - snw_pc_s08
  - snw_pc_s09
  - snw_pc_s10
  - snw_pc_s11
  - snw_pc_s12
  - snw_pc_smx
  - snw_pc_syr
  - soc_th_sav
  - swc_pc_s01
  - swc_pc_s02
  - swc_pc_s03
  - swc_pc_s04
  - swc_pc_s05
  - swc_pc_s06
  - swc_pc_s07
  - swc_pc_s08
  - swc_pc_s09
  - swc_pc_s10
  - swc_pc_s11
  - swc_pc_s12
  - swc_pc_syr
  - tbi_cl_smj
  - tec_cl_smj
  - tmp_dc_s01
  - tmp_dc_s02
  - tmp_dc_s03
  - tmp_dc_s04
  - tmp_dc_s05
  - tmp_dc_s06
  - tmp_dc_s07
  - tmp_dc_s08
  - tmp_dc_s09
  - tmp_dc_s10
  - tmp_dc_s11
  - tmp_dc_s12
  - tmp_dc_smn
  - tmp_dc_smx
  - tmp_dc_syr
  - urb_pc_sse
  - wet_cl_smj
  - wet_pc_s01
  - wet_pc_s02
  - wet_pc_s03
  - wet_pc_s04
  - wet_pc_s05
  - wet_pc_s06
  - wet_pc_s07
  - wet_pc_s08
  - wet_pc_s09
  - wet_pc_sg1
  - wet_pc_sg2
  - aridity_ERA5_LAND
  - aridity_FAO_PM
  - frac_snow
  - high_prec_dur
  - high_prec_freq
  - low_prec_dur
  - low_prec_freq
  - moisture_index_ERA5_LAND
  - moisture_index_FAO_PM
  - p_mean
  - pet_mean_ERA5_LAND
  - pet_mean_FAO_PM
  - seasonality_ERA5_LAND
  - seasonality_FAO_PM

# clip negative predictions to zero for all variables listed below. Should be a list, even for single variables.
clip_targets_to_zero:
  - streamflow
