# --- Experiment configurations --------------------------------------------------------------------

# experiment name, used as folder name
experiment_name: LSTM-300CL-ft

# files to specify training, validation and test basins (relative to code root or absolute path)
train_basin_file: basin_lists/Uba_basin.txt
validation_basin_file: basin_lists/Uba_basin.txt
test_basin_file: basin_lists/Uba_basin.txt

# --- Training configuration -----------------------------------------------------------------------

# specify learning rates to use starting at specific epochs (0 is the initial learning rate)
learning_rate: 5e-5	

# Number of training epochs
epochs: 20

finetune_modules:
- head
- lstm

base_run_dir: configs/NCL/LSTM-300CL